feat!: switch to Just from Makefile

diff --git a/install b/install
--- a/install
+++ b/install
@@ -13,15 +13,18 @@ is_exist() {
 install() {
 	if [ -d "${DOT_DIRECTORY}" ]; then
 		echo "DOTFILES have be already installed"
-		exit 1
+	else 
+		if is_exist "git"; then
+			git clone --recursive "${REMOTE_URL}" "${DOT_DIRECTORY}"
+		else
+			echo "git required"
+			exit 1
+		fi
 	fi
-	
-	if is_exist "git"; then
-		git clone --recursive "${REMOTE_URL}" "${DOT_DIRECTORY}"
-	else
-		echo "git required"
-		exit 1
-	fi
+
+	echo ""
+	echo "Start to setup DOTFILES"
+	echo ""
 
 	cd "${DOT_DIRECTORY}"
 	
@@ -33,7 +36,22 @@ install() {
 		bash ./init/init-macos.sh
 	fi
 
-	make install
+	if is_exist ./bin/just; then
+		echo "just is installed"
+		./bin/just --version || { echo "just command not working"; exit 1; }
+	else
+		# create ./bin
+		mkdir -p ./bin
+
+		# download and extract just to ./bin/just
+		curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ./bin
+
+		# just should now be executable
+		./bin/just --version || { echo "just install failed"; exit 1; }
+		echo "just install succeeded"
+	fi
+
+	./bin/just install
 }
 
 install
